import { notFound, redirect } from "next/navigation";
import Link from "next/link";
import { getLead } from "@/lib/queries/leads";
import { listAllProducts } from "@/lib/queries/products";
import { getCurrentUser } from "@/lib/supabase/current-user";
import { createClient } from "@/lib/supabase/server";
import { PrintLeadButton } from "@/components/leads/print-lead-button";
import {
  displayName,
  formatCurrency,
  formatDate,
  productLabel,
} from "@/lib/format";
import { COMPANY_FACILITY_ADDRESS } from "@/lib/constants";
import type { LeadProductLineItem } from "@/app/(app)/leads/actions";

function Field({ label, value }: { label: string; value: React.ReactNode }) {
  return (
    <div className="flex flex-col gap-0.5">
      <dt className="text-xs uppercase tracking-wide text-neutral-500">{label}</dt>
      <dd className="text-sm text-neutral-900">{value || "—"}</dd>
    </div>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section className="break-inside-avoid border-t border-neutral-200 py-4 first:border-none first:pt-0">
      <h2 className="mb-3 text-sm font-semibold uppercase tracking-wide text-neutral-700">
        {title}
      </h2>
      <dl className="grid grid-cols-2 gap-x-6 gap-y-3">{children}</dl>
    </section>
  );
}

function lineItemName(item: LeadProductLineItem, products: { id: string; item_number: string; name: string }[]) {
  if (item.productId) {
    const product = products.find((p) => p.id === item.productId);
    return product ? productLabel(product) : "Unknown product";
  }
  return `${item.customProductName ?? "Custom product"} (Custom)`;
}

export default async function LeadPrintPage(props: {
  params: Promise<{ id: string }>;
}) {
  const { id } = await props.params;
  const currentUser = await getCurrentUser();
  if (!currentUser) redirect("/login");

  let lead;
  let lineItems: LeadProductLineItem[];
  try {
    ({ lead, lineItems } = await getLead(id));
  } catch {
    notFound();
  }
  // Details are masked for anyone but the owner/admin — nothing to print.
  if (currentUser.role !== "admin" && currentUser.id !== lead.salesperson_id) notFound();

  const products = await listAllProducts();

  const supabase = await createClient();
  const { data: salesperson } = await supabase
    .from("profiles")
    .select("full_name, email")
    .eq("id", lead.salesperson_id)
    .single();

  const salespersonName = salesperson
    ? displayName(salesperson.full_name, salesperson.email)
    : "Unknown";

  return (
    <div className="mx-auto max-w-3xl bg-white p-6 text-neutral-900 print:bg-white print:text-black md:p-10">
      <div className="mb-6 flex items-start justify-between print:hidden">
        <Link href={`/leads/${id}`} className="text-sm text-neutral-500 hover:underline">
          &larr; Back to lead
        </Link>
        <PrintLeadButton />
      </div>

      <header className="mb-6 flex items-baseline justify-between border-b border-neutral-300 pb-4">
        <div>
          <p className="text-xs uppercase tracking-wide text-neutral-500">
            Klein Pickle Company — Lead Summary
          </p>
          <h1 className="text-2xl font-semibold">{lead.company_name}</h1>
        </div>
        <div className="text-right text-xs text-neutral-500">
          <p>Printed {formatDate(new Date().toISOString().slice(0, 10))}</p>
          <p>By {displayName(currentUser.full_name, currentUser.email)}</p>
        </div>
      </header>

      <Section title="Basic info">
        <Field label="Salesperson / lead generated by" value={salespersonName} />
        <Field label="Primary contact" value={lead.primary_contact_name} />
        <Field label="Contact email" value={lead.contact_email} />
        <Field label="Contact phone" value={lead.contact_phone} />
        <Field label="Date lead created" value={formatDate(lead.lead_date)} />
        <Field label="Lead source" value={lead.lead_source} />
        <Field label="Specific source" value={lead.specific_source} />
      </Section>

      <Section title="Opportunity details">
        <Field label="Customer type" value={lead.customer_type} />
      </Section>

      <section className="break-inside-avoid border-t border-neutral-200 py-4">
        <h2 className="mb-3 text-sm font-semibold uppercase tracking-wide text-neutral-700">
          Products interested in &amp; sizes
        </h2>
        {lineItems.length > 0 ? (
          <table className="w-full border-collapse text-sm">
            <thead>
              <tr className="border-b border-neutral-300 text-left text-xs uppercase tracking-wide text-neutral-500">
                <th className="py-1 pr-2">Product</th>
                <th className="py-1 pr-2">Pack size(s)</th>
                <th className="py-1 pr-2">Proposed vol.</th>
                <th className="py-1 pr-2">Est. annual vol.</th>
                <th className="py-1 pr-2">Est. annual sales</th>
                <th className="py-1 pr-2">Target price</th>
                <th className="py-1">Specs</th>
              </tr>
            </thead>
            <tbody>
              {lineItems.map((item, index) => {
                const sizeLabel =
                  item.packSizes.length > 0
                    ? item.packSizes
                        .map((s) =>
                          s === "Other" && item.customPackSize
                            ? `Other (${item.customPackSize})`
                            : s,
                        )
                        .join(", ")
                    : "—";
                return (
                  <tr key={index} className="border-b border-neutral-100 align-top">
                    <td className="py-1.5 pr-2 font-medium">{lineItemName(item, products)}</td>
                    <td className="py-1.5 pr-2">{sizeLabel}</td>
                    <td className="py-1.5 pr-2">
                      {item.proposedVolume ? `${item.proposedVolume} ${item.volumeUnit ?? "units"}` : "—"}
                    </td>
                    <td className="py-1.5 pr-2">
                      {item.estimatedAnnualVolume
                        ? `${item.estimatedAnnualVolume} ${item.volumeUnit ?? "units"}/yr`
                        : "—"}
                    </td>
                    <td className="py-1.5 pr-2">{formatCurrency(item.estimatedAnnualSales)}</td>
                    <td className="py-1.5 pr-2">{formatCurrency(item.targetPrice)}</td>
                    <td className="py-1.5">{item.customSpecs || "—"}</td>
                  </tr>
                );
              })}
            </tbody>
          </table>
        ) : (
          <p className="text-sm text-neutral-500">No products added.</p>
        )}
      </section>

      <Section title="Commercial terms">
        <Field label="Freight terms" value={lead.freight_terms} />
        <Field label="Distributor" value={lead.distributor} />
        {lead.freight_terms === "FOB Origin" ? (
          <Field
            label="Ship-to"
            value={`Klein Pickle facility — ${COMPANY_FACILITY_ADDRESS}`}
          />
        ) : (
          <Field
            label="Ship-to address"
            value={[lead.ship_to_address, lead.ship_to_city, lead.ship_to_state, lead.ship_to_zip, lead.ship_to_country]
              .filter(Boolean)
              .join(", ")}
          />
        )}
        <Field label="Broker involved" value={lead.broker_involved ? "Yes" : "No"} />
        {lead.broker_involved ? (
          <>
            <Field label="Broker name" value={lead.broker_name} />
            <Field label="Broker company" value={lead.broker_company} />
            <Field
              label="Broker commission"
              value={lead.broker_commission_pct !== null ? `${lead.broker_commission_pct}%` : null}
            />
          </>
        ) : null}
      </Section>

      <Section title="Sample & competitive landscape">
        <Field label="Sample required" value={lead.sample_required ? "Yes" : "No"} />
        <Field label="Sample / trial status" value={lead.sample_trial_status} />
        <Field label="Current supplier" value={lead.current_supplier} />
        <Field label="Expected start date" value={formatDate(lead.expected_start_date)} />
        <div className="col-span-2">
          <Field label="Reason for opportunity" value={lead.reason_for_opportunity} />
        </div>
      </Section>

      <Section title="Stage & follow-up">
        <Field label="Sales stage" value={lead.sales_stage} />
        <Field
          label="Probability to close"
          value={lead.probability_to_close !== null ? `${lead.probability_to_close}%` : null}
        />
        <Field label="Next action" value={lead.next_action} />
        <Field label="Next follow-up date" value={formatDate(lead.next_follow_up_date)} />
        {lead.sales_stage === "Lost" ? (
          <div className="col-span-2">
            <Field label="Lost reason" value={lead.lost_reason} />
          </div>
        ) : null}
        <div className="col-span-2">
          <Field label="Notes / requirements" value={lead.notes} />
        </div>
      </Section>
    </div>
  );
}
