"use client";

import { useState, useTransition } from "react";
import { useRouter } from "next/navigation";
import { toast } from "sonner";
import { createLead, updateLead, type LeadInput } from "@/app/(app)/leads/actions";
import type { Database } from "@/lib/database.types";
import {
  SALES_STAGES,
  STAGE_DEFAULT_PROBABILITY,
  LEAD_SOURCES,
  CUSTOMER_TYPES,
  FREIGHT_TERMS_OPTIONS,
  SAMPLE_TRIAL_STATUSES,
} from "@/lib/constants";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Checkbox } from "@/components/ui/checkbox";
import { Switch } from "@/components/ui/switch";
import {
  Card,
  CardContent,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";

type Lead = Database["public"]["Tables"]["leads"]["Row"];
type Profile = Database["public"]["Tables"]["profiles"]["Row"];
type Product = Database["public"]["Tables"]["products"]["Row"];

function todayISO() {
  return new Date().toISOString().slice(0, 10);
}

export function LeadForm({
  mode,
  lead,
  initialProductIds = [],
  salespeople,
  products,
  currentUser,
}: {
  mode: "create" | "edit";
  lead?: Lead;
  initialProductIds?: string[];
  salespeople: Profile[];
  products: Product[];
  currentUser: Profile;
}) {
  const router = useRouter();
  const [isPending, startTransition] = useTransition();
  const [probabilityTouched, setProbabilityTouched] = useState(mode === "edit");

  const [values, setValues] = useState<LeadInput>(
    lead ?? {
      salesperson_id: currentUser.id,
      company_name: "",
      lead_date: todayISO(),
      sales_stage: "New Lead",
      probability_to_close: STAGE_DEFAULT_PROBABILITY["New Lead"],
      sample_required: false,
      broker_involved: false,
      sample_trial_status: "Not Required",
    },
  );
  const [productIds, setProductIds] = useState<string[]>(initialProductIds);

  function set<K extends keyof LeadInput>(key: K, value: LeadInput[K]) {
    setValues((prev) => ({ ...prev, [key]: value }));
  }

  function onStageChange(stage: string | null) {
    if (!stage) return;
    setValues((prev) => ({
      ...prev,
      sales_stage: stage as LeadInput["sales_stage"],
      probability_to_close: probabilityTouched
        ? prev.probability_to_close
        : STAGE_DEFAULT_PROBABILITY[stage as keyof typeof STAGE_DEFAULT_PROBABILITY],
    }));
  }

  function toggleProduct(id: string) {
    setProductIds((prev) =>
      prev.includes(id) ? prev.filter((p) => p !== id) : [...prev, id],
    );
  }

  function onSubmit(e: React.FormEvent) {
    e.preventDefault();
    startTransition(async () => {
      try {
        if (mode === "create") {
          await createLead(values, productIds);
        } else if (lead) {
          await updateLead(lead.id, values, productIds);
          toast.success("Lead updated");
          router.refresh();
        }
      } catch (err) {
        toast.error(err instanceof Error ? err.message : "Something went wrong");
      }
    });
  }

  const canPickSalesperson = currentUser.role === "admin";

  return (
    <form onSubmit={onSubmit} className="flex flex-col gap-4 pb-24 md:pb-6">
      <Card>
        <CardHeader>
          <CardTitle className="text-base">Basic info</CardTitle>
        </CardHeader>
        <CardContent className="grid gap-4 sm:grid-cols-2">
          <div className="flex flex-col gap-2">
            <Label>Salesperson / Lead generated by</Label>
            {canPickSalesperson ? (
              <Select
                value={values.salesperson_id}
                onValueChange={(v) => v && set("salesperson_id", v)}
              >
                <SelectTrigger>
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  {salespeople.map((p) => (
                    <SelectItem key={p.id} value={p.id}>
                      {p.full_name ?? p.email}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            ) : (
              <Input value={currentUser.full_name ?? currentUser.email ?? ""} disabled />
            )}
          </div>
          <div className="flex flex-col gap-2">
            <Label htmlFor="company_name">Lead / company name</Label>
            <Input
              id="company_name"
              required
              value={values.company_name}
              onChange={(e) => set("company_name", e.target.value)}
            />
          </div>
          <div className="flex flex-col gap-2">
            <Label htmlFor="primary_contact_name">Primary contact</Label>
            <Input
              id="primary_contact_name"
              value={values.primary_contact_name ?? ""}
              onChange={(e) => set("primary_contact_name", e.target.value)}
            />
          </div>
          <div className="flex flex-col gap-2">
            <Label htmlFor="contact_email">Contact email</Label>
            <Input
              id="contact_email"
              type="email"
              value={values.contact_email ?? ""}
              onChange={(e) => set("contact_email", e.target.value)}
            />
          </div>
          <div className="flex flex-col gap-2">
            <Label htmlFor="contact_phone">Contact phone</Label>
            <Input
              id="contact_phone"
              type="tel"
              value={values.contact_phone ?? ""}
              onChange={(e) => set("contact_phone", e.target.value)}
            />
          </div>
          <div className="flex flex-col gap-2">
            <Label htmlFor="lead_date">Date lead created</Label>
            <Input
              id="lead_date"
              type="date"
              value={values.lead_date ?? todayISO()}
              onChange={(e) => set("lead_date", e.target.value)}
            />
          </div>
          <div className="flex flex-col gap-2">
            <Label>Lead source</Label>
            <Select
              value={values.lead_source ?? undefined}
              onValueChange={(v) => set("lead_source", v as LeadInput["lead_source"])}
            >
              <SelectTrigger>
                <SelectValue placeholder="Select a source" />
              </SelectTrigger>
              <SelectContent>
                {LEAD_SOURCES.map((s) => (
                  <SelectItem key={s} value={s}>
                    {s}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
          </div>
          <div className="flex flex-col gap-2">
            <Label htmlFor="specific_source">Specific source</Label>
            <Input
              id="specific_source"
              placeholder="e.g. IFT Trade Show 2026"
              value={values.specific_source ?? ""}
              onChange={(e) => set("specific_source", e.target.value)}
            />
          </div>
        </CardContent>
      </Card>

      <Card>
        <CardHeader>
          <CardTitle className="text-base">Opportunity details</CardTitle>
        </CardHeader>
        <CardContent className="grid gap-4 sm:grid-cols-2">
          <div className="flex flex-col gap-2">
            <Label>Customer type</Label>
            <Select
              value={values.customer_type ?? undefined}
              onValueChange={(v) => set("customer_type", v as LeadInput["customer_type"])}
            >
              <SelectTrigger>
                <SelectValue placeholder="Select a type" />
              </SelectTrigger>
              <SelectContent>
                {CUSTOMER_TYPES.map((t) => (
                  <SelectItem key={t} value={t}>
                    {t}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
          </div>
          <div className="flex flex-col gap-2">
            <Label htmlFor="pack_size_format">Pack size / format</Label>
            <Input
              id="pack_size_format"
              placeholder="e.g. 16oz jar, 12/case"
              value={values.pack_size_format ?? ""}
              onChange={(e) => set("pack_size_format", e.target.value)}
            />
          </div>
          <div className="flex flex-col gap-2 sm:col-span-2">
            <Label>Products interested in</Label>
            <div className="flex flex-wrap gap-3 rounded-md border p-3">
              {products.length === 0 ? (
                <p className="text-sm text-muted-foreground">
                  No products in the catalog yet — add some in Admin.
                </p>
              ) : (
                products.map((product) => (
                  <label
                    key={product.id}
                    className="flex items-center gap-2 text-sm"
                  >
                    <Checkbox
                      checked={productIds.includes(product.id)}
                      onCheckedChange={() => toggleProduct(product.id)}
                    />
                    {product.name}
                  </label>
                ))
              )}
            </div>
          </div>
          <div className="flex flex-col gap-2">
            <Label htmlFor="proposed_volume">Proposed volume</Label>
            <Input
              id="proposed_volume"
              type="number"
              value={values.proposed_volume ?? ""}
              onChange={(e) =>
                set("proposed_volume", e.target.value ? Number(e.target.value) : null)
              }
            />
          </div>
          <div className="flex flex-col gap-2">
            <Label htmlFor="volume_unit">Volume unit</Label>
            <Input
              id="volume_unit"
              placeholder="e.g. cases, pallets, lbs"
              value={values.volume_unit ?? ""}
              onChange={(e) => set("volume_unit", e.target.value)}
            />
          </div>
          <div className="flex flex-col gap-2">
            <Label htmlFor="estimated_annual_volume">Estimated annual volume</Label>
            <Input
              id="estimated_annual_volume"
              type="number"
              value={values.estimated_annual_volume ?? ""}
              onChange={(e) =>
                set(
                  "estimated_annual_volume",
                  e.target.value ? Number(e.target.value) : null,
                )
              }
            />
          </div>
          <div className="flex flex-col gap-2">
            <Label htmlFor="estimated_annual_sales">Estimated annual sales ($)</Label>
            <Input
              id="estimated_annual_sales"
              type="number"
              value={values.estimated_annual_sales ?? ""}
              onChange={(e) =>
                set(
                  "estimated_annual_sales",
                  e.target.value ? Number(e.target.value) : null,
                )
              }
            />
          </div>
          <div className="flex flex-col gap-2">
            <Label htmlFor="target_price">Target price ($)</Label>
            <Input
              id="target_price"
              type="number"
              step="0.01"
              value={values.target_price ?? ""}
              onChange={(e) =>
                set("target_price", e.target.value ? Number(e.target.value) : null)
              }
            />
          </div>
        </CardContent>
      </Card>

      <Card>
        <CardHeader>
          <CardTitle className="text-base">Commercial terms</CardTitle>
        </CardHeader>
        <CardContent className="grid gap-4 sm:grid-cols-2">
          <div className="flex flex-col gap-2">
            <Label>Freight terms</Label>
            <Select
              value={values.freight_terms ?? undefined}
              onValueChange={(v) => set("freight_terms", v as LeadInput["freight_terms"])}
            >
              <SelectTrigger>
                <SelectValue placeholder="Select freight terms" />
              </SelectTrigger>
              <SelectContent>
                {FREIGHT_TERMS_OPTIONS.map((f) => (
                  <SelectItem key={f} value={f}>
                    {f}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
          </div>
          <div className="flex flex-col gap-2">
            <Label htmlFor="distributor">Distributor</Label>
            <Input
              id="distributor"
              value={values.distributor ?? ""}
              onChange={(e) => set("distributor", e.target.value)}
            />
          </div>
          <div className="flex flex-col gap-2 sm:col-span-2">
            <Label htmlFor="ship_to_locations">Ship-to locations</Label>
            <Textarea
              id="ship_to_locations"
              rows={2}
              value={values.ship_to_locations ?? ""}
              onChange={(e) => set("ship_to_locations", e.target.value)}
            />
          </div>
          <div className="flex items-center justify-between rounded-md border p-3">
            <Label htmlFor="broker_involved">Broker involved</Label>
            <Switch
              id="broker_involved"
              checked={values.broker_involved ?? false}
              onCheckedChange={(v) => set("broker_involved", v)}
            />
          </div>
          {values.broker_involved ? (
            <div className="flex flex-col gap-2">
              <Label htmlFor="broker_commission_pct">Broker commission %</Label>
              <Input
                id="broker_commission_pct"
                type="number"
                step="0.1"
                value={values.broker_commission_pct ?? ""}
                onChange={(e) =>
                  set(
                    "broker_commission_pct",
                    e.target.value ? Number(e.target.value) : null,
                  )
                }
              />
            </div>
          ) : null}
        </CardContent>
      </Card>

      <Card>
        <CardHeader>
          <CardTitle className="text-base">Sample &amp; competitive landscape</CardTitle>
        </CardHeader>
        <CardContent className="grid gap-4 sm:grid-cols-2">
          <div className="flex items-center justify-between rounded-md border p-3">
            <Label htmlFor="sample_required">Sample required</Label>
            <Switch
              id="sample_required"
              checked={values.sample_required ?? false}
              onCheckedChange={(v) => set("sample_required", v)}
            />
          </div>
          <div className="flex flex-col gap-2">
            <Label>Sample / trial status</Label>
            <Select
              value={values.sample_trial_status ?? "Not Required"}
              onValueChange={(v) =>
                set("sample_trial_status", v as LeadInput["sample_trial_status"])
              }
            >
              <SelectTrigger>
                <SelectValue />
              </SelectTrigger>
              <SelectContent>
                {SAMPLE_TRIAL_STATUSES.map((s) => (
                  <SelectItem key={s} value={s}>
                    {s}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
          </div>
          <div className="flex flex-col gap-2">
            <Label htmlFor="current_supplier">Current supplier</Label>
            <Input
              id="current_supplier"
              value={values.current_supplier ?? ""}
              onChange={(e) => set("current_supplier", e.target.value)}
            />
          </div>
          <div className="flex flex-col gap-2">
            <Label htmlFor="expected_start_date">Expected start date</Label>
            <Input
              id="expected_start_date"
              type="date"
              value={values.expected_start_date ?? ""}
              onChange={(e) => set("expected_start_date", e.target.value)}
            />
          </div>
          <div className="flex flex-col gap-2 sm:col-span-2">
            <Label htmlFor="reason_for_opportunity">Reason for opportunity</Label>
            <Textarea
              id="reason_for_opportunity"
              rows={2}
              value={values.reason_for_opportunity ?? ""}
              onChange={(e) => set("reason_for_opportunity", e.target.value)}
            />
          </div>
        </CardContent>
      </Card>

      <Card>
        <CardHeader>
          <CardTitle className="text-base">Stage &amp; follow-up</CardTitle>
        </CardHeader>
        <CardContent className="grid gap-4 sm:grid-cols-2">
          <div className="flex flex-col gap-2">
            <Label>Sales stage</Label>
            <Select value={values.sales_stage} onValueChange={onStageChange}>
              <SelectTrigger>
                <SelectValue />
              </SelectTrigger>
              <SelectContent>
                {SALES_STAGES.map((s) => (
                  <SelectItem key={s} value={s}>
                    {s}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
          </div>
          <div className="flex flex-col gap-2">
            <Label htmlFor="probability_to_close">Probability to close (%)</Label>
            <Input
              id="probability_to_close"
              type="number"
              min={0}
              max={100}
              value={values.probability_to_close ?? ""}
              onChange={(e) => {
                setProbabilityTouched(true);
                set(
                  "probability_to_close",
                  e.target.value ? Number(e.target.value) : null,
                );
              }}
            />
          </div>
          <div className="flex flex-col gap-2">
            <Label htmlFor="next_action">Next action</Label>
            <Input
              id="next_action"
              value={values.next_action ?? ""}
              onChange={(e) => set("next_action", e.target.value)}
            />
          </div>
          <div className="flex flex-col gap-2">
            <Label htmlFor="next_follow_up_date">Next follow-up date</Label>
            <Input
              id="next_follow_up_date"
              type="date"
              value={values.next_follow_up_date ?? ""}
              onChange={(e) => set("next_follow_up_date", e.target.value)}
            />
          </div>
          {values.sales_stage === "Lost" ? (
            <div className="flex flex-col gap-2 sm:col-span-2">
              <Label htmlFor="lost_reason">Lost reason</Label>
              <Textarea
                id="lost_reason"
                rows={2}
                value={values.lost_reason ?? ""}
                onChange={(e) => set("lost_reason", e.target.value)}
              />
            </div>
          ) : null}
          <div className="flex flex-col gap-2 sm:col-span-2">
            <Label htmlFor="notes">Notes / requirements</Label>
            <Textarea
              id="notes"
              rows={3}
              value={values.notes ?? ""}
              onChange={(e) => set("notes", e.target.value)}
            />
          </div>
        </CardContent>
      </Card>

      <div className="fixed inset-x-0 bottom-16 z-30 border-t bg-background p-3 md:static md:border-none md:bg-transparent md:p-0">
        <Button type="submit" disabled={isPending} className="w-full md:w-auto">
          {isPending ? "Saving…" : mode === "create" ? "Create lead" : "Save changes"}
        </Button>
      </div>
    </form>
  );
}
